### ISSUE TITLE
What instructions set of RISC-V do I need to run doom?

### ISSUE THREAD

**Issue by hyf6661669** [lcq2/risc-666#1]
Your work is very insteresting! I also want to put my own risc-v core on my FPGA and run doom on it. I'm wondering if rv32im enough to run doom? Thanks!

What's more, it seems that some header files are missing, such as ```rv_elf.h``` and ```memory.h```

**Comment by lcq2** [comment]
Hi, thanks for pointing this out. You can checkout commit 4f77d939e9de8733fc7bb9bc101eae07aa83c9ae for a stable one. Current master won't build because of OSX compatibility and some new code that I still need to push (and I don't have access to it right now). I did not have much time lately to work on this, I'm really sorry.

As for the instruction set needed, rv32im is more than enough, but be sure to build the RISC-V compiler to only output instruction for that specific set. Technically for DooM you just need integer instructions, some new versions of doom replaced fixed point division with floating point one, but in the version I'm using, I restored fixed point division.

**Comment by lcq2** [comment]
fixed, now master should build without issues
